name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  push-to-artifactory:
    name: Test and publish snapshot to artifactory
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 11
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: '11'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: maven

      - name: Check version from pom.xml
        id: check_version
        run: |
          PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION: ${PROJECT_VERSION}"
          if [[ ${PROJECT_VERSION} != *-SNAPSHOT ]]; then
            echo "Error: version must be suffixed with '-SNAPSHOT'. Concrete versions can only be released from master branch"
            exit 1
          fi

      - name: Test
        run: mvn --no-transfer-progress clean verify

      - name: Install gpg key
        run: echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | base64 --decode | gpg --batch --import

      - name: Maven deploy
        run: mvn --no-transfer-progress --batch-mode -DskipTests deploy -P release
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Upload to codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          file: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
